stages:
  - init
  - test
  - build
  - deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds
  VENV_PY34: C:\temp\builds\python34_x64
  PYPI_URL: http://tphweb.tph.local/pypi

# Set environment vars
before_script:
  - REM ==================== Before Script ====================
  - echo %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"
  - REM ~~~~~~~~~~~~~~~~~~~~ End Before Script ~~~~~~~~~~~~~~~~~~~~

pip_install:
  stage: init
  when: always
  tags:
    - python
  script:
    - REM ==================== pip_install ====================
    # Clear pip cache because it sometimes causes issues.
    - rd /S /Q C:\Users\tph-buildbot\AppData\Local\pip\Cache

    - python -m venv --clear %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    # Can't upgrade pip in place.
    # See https://github.com/pypa/pip/issues/1299#issuecomment-188198496
    - python -m pip install --upgrade pip==8.1.0 --no-cache-dir

    # Scipy doesn't have a wheel on PyPI, so I need to install it
    # from a downloaded wheel. Also means I can't use `pip install -r
    # requirements.txt` to install any other items :-(
#    - pip install -r requirements.txt --no-cache-dir
    - pip install https://gitlab.com/dougthor42/wheels/raw/master/numpy-1.11.0+mkl-cp34-cp34m-win_amd64.whl --no-cache-dir
    - pip install .\build_reqs\scipy-0.17.0-cp34-none-win_amd64.whl
    - pip install matplotlib --no-cache-dir
    - pip install colorama --no-cache-dir
    - pip install -r dev-requirements.txt --no-cache-dir

tests:
  stage: test
  when: on_success
  tags:
    - python
  script:
    - REM ==================== tests ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - pip install nose2 --no-cache-dir
    - green -vvv -s 1 -W -t douglib
    - nose2 douglib

build:
  stage: build
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - REM ==================== tag_bundle ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*

deploy:
  stage: deploy
  environment:
    name: production
    url: $PYPI_URL/simple/douglib
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python -m pip install --upgrade twine
    - dir dist\*.zip /b/s > temp.txt
    # Read that path into an environment variable.
    - set /p VAR=<temp.txt
    - echo %VAR%
    - twine register --repository %PYPI_URL% --repository-url %PYPI_URL% -u '' -p '' %VAR%
    - twine upload --repository %PYPI_URL% --repository-url %PYPI_URL% -u '' -p '' dist/*

clean_up:
  stage: cleanup
  when: always
  tags:
    - python
  script:
    - REM ==================== clean_up ====================
    - rd /S /Q %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
