stages:
  - init
  - test
  - tag_deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds
  VENV_PY34: C:\temp\builds\python34_x64

# Set environment vars
before_script:
  - REM ==================== Before Script ====================
  - echo %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

  # Clear pip cache because it sometimes causes issues.
  - rd /S /Q C:\Users\tph-buildbot\AppData\Local\pip\Cache
  - REM ~~~~~~~~~~~~~~~~~~~~ End Before Script ~~~~~~~~~~~~~~~~~~~~

pip_install:
  stage: init
  when: always
  tags:
    - python
  script:
    - REM ==================== pip_install ====================
    - python -m venv --clear %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    # Can't upgrade pip in place.
    # See https://github.com/pypa/pip/issues/1299#issuecomment-188198496
    - python -m pip install --upgrade pip==8.1.0 --no-cache-dir
    - pip install -r requirements.txt --no-cache-dir
    - pip install -r dev-requirements.txt --no-cache-dir

tests:
  stage: test
  when: on_success
  tags:
    - python
  script:
    - REM ==================== tests ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - green -vvv -s 1 -W -t douglib

tag_bundle:
  stage: tag_deploy
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - REM ==================== tag_bundle ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

clean_up:
  stage: cleanup
  when: always
  tags:
    - python
  script:
    - REM ==================== clean_up ====================
    - rd /S /Q %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
