#################################
# General setup
#################################
language: python

sudo: false

matrix:
  include:
  - python: "3.4"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
# command to install dependencies
before_install:
  - echo "----- before_install -----"

install:
  - echo "----- install -----"

  # Start the install of everything
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - echo "----- script -----"
  - python -c "import sys;print(sys.version);print(sys.path)"
  - green douglib -vvv --run-coverage

after_success:
  - echo "----- after_success -----"

  # Send coverage information to coveralls.io
  - coveralls
