### ----------------------
### General Configuration
### ----------------------

environment:
  global:
    WXPYTHON_SNAPSHOTS: "https://wxpython.org/Phoenix/snapshot-builds"

  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"

  # install dependencies
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  #- "%CMD_IN_ENV% nosetests"
  - "%PYTHON%\\python.exe -m green douglib -vvv -t -s 1"

after_test:
#  # if tests OK, create whl package
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

